name: Publish Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: write   # needed to create release & push tags
  id-token: write   # needed for PyPI trusted publishing

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so tags are available

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Configure Git
        run: |
          git config --global user.email "aerithnetzer@northwestern.edu"
          git config --global user.name "KyberwarlordBot"

      - name: Install bump2version
        run: python -m pip install bump2version build

      - name: Bump version and tag
        id: bump
        run: |
          # Bump patch version (you can change to major/minor)
          bump2version patch --allow-dirty --tag --commit
          NEW_VERSION=$(git describe --tags --abbrev=0)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git push origin main --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.version }}
          name: "Release ${{ steps.bump.outputs.version }}"
          draft: false
          prerelease: false

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build

    environment:
      name: pypi
      url: https://pypi.org/project/woolworm/${{ needs.release-build.outputs.version }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
